{{- $hc := index .Values "homelab-common" | default dict }}
{{- range $hc.authentikBlueprints | default list }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/part-of: authentik
data:
  {{- range $filename, $content := .blueprints }}
  {{ $filename }}: |
{{ $content | indent 4 }}
  {{- end }}
{{- end }}
