{{- $hc := index .Values "homelab-common" | default dict }}
{{- $dbs := list }}
{{- if $hc.cnpgDatabase }}
{{-   $dbs = append $dbs $hc.cnpgDatabase }}
{{- end }}
{{- if $hc.cnpgDatabases }}
{{-   $dbs = concat $dbs $hc.cnpgDatabases }}
{{- end }}
{{- range $db := $dbs }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: {{ $db.name }}
  namespace: {{ $db.namespace | default $.Release.Namespace }}
spec:
  name: {{ $db.name }}
  owner: {{ $db.owner }}
  cluster:
    name: {{ $db.clusterName }}
  {{- if $db.extensions }}
  extensions:
    {{- range $db.extensions }}
    - name: {{ .name }}
      ensure: present
    {{- end }}
  {{- end }}
  ensure: present
{{- end }}
