{{- $hc := index .Values "homelab-common" | default dict }}
{{- $pvcs := $hc.persistentVolumeClaims | default list }}
{{- range $pvcs }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  {{- with .labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .accessModes }}
    - {{ . }}
    {{- end }}
  {{- if .volumeName }}
  volumeName: {{ .volumeName }}
  {{- end }}
  volumeMode: {{ .volumeMode | default "Filesystem" }}
  resources:
    requests:
      storage: {{ .size }}
  {{- if .storageClassName }}
  storageClassName: {{ .storageClassName }}
  {{- end }}
{{- end }}
