chart: longhorn
repoURL: https://charts.longhorn.io
targetRevision: "1.12.0"
namespace: longhorn-system
wave: "-4"
extraManifests: true
ignoreDiff: |
  - group: longhorn.io
    kind: BackupTarget
    name: default
    jqPathExpressions:
      - .spec.syncRequestedAt
