apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  syncPolicy:
    applicationsSync: create-update
    preserveResourcesOnDeletion: true
  generators:
    - git:
        repoURL: ssh://git@forgejo-ssh.forgejo.svc.cluster.local:22/vizzle/homelab.git
        revision: HEAD
        files:
          - path: argocd/apps/*/config.yaml
  template:
    metadata:
      name: "{{ .path.basename }}"
      namespace: argocd
    spec:
      project: applications
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ dig \"namespace\" .path.basename . }}"
  templatePatch: |
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "{{ .wave }}"
      labels:
        app.kubernetes.io/managed-by: argocd-applicationset
        app.kubernetes.io/part-of: applications
      finalizers:
        - resources-finalizer.argocd.argoproj.io/background
    spec:
      sources:
        {{- if not (index . "homelabOnly") }}
        - repoURL: "{{ .repoURL }}"
          chart: "{{ dig "chart" .path.basename . }}"
          targetRevision: "{{ dig "targetRevision" "*" . }}"
          helm:
            valueFiles:
              - "$values/argocd/apps/{{ .path.basename }}/values.yaml"
        {{- end }}
        {{- if index . "cnpgValuesFile" }}
        - repoURL: https://cloudnative-pg.github.io/charts
          chart: cluster
          targetRevision: "0.6.1"
          helm:
            valueFiles:
              - "$values/argocd/apps/{{ .path.basename }}/{{ .cnpgValuesFile }}"
        {{- end }}
        - repoURL: https://git.example.com/api/packages/vizzle/helm
          chart: homelab-common
          targetRevision: "1.8.4"
          helm:
            valueFiles:
              - "$values/argocd/values/shared/global.yaml"
              - "$values/argocd/apps/{{ .path.basename }}/{{ dig "homelabValuesFile" "values.yaml" . }}"
        - repoURL: ssh://git@forgejo-ssh.forgejo.svc.cluster.local:22/vizzle/homelab.git
          targetRevision: HEAD
          ref: values
        {{- if index . "extraManifests" }}
        - repoURL: ssh://git@forgejo-ssh.forgejo.svc.cluster.local:22/vizzle/homelab.git
          targetRevision: HEAD
          path: "argocd/apps/{{ .path.basename }}/manifests"
        {{- end }}
      {{- if index . "ignoreDiff" }}
      ignoreDifferences:
      {{- .ignoreDiff | nindent 4 }}
      {{- end }}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - RespectIgnoreDifferences=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
