apiVersion: v1
kind: Secret
metadata:
  name: forgejo-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: forgejo-helm
  type: helm
  url: code.forgejo.org/forgejo-helm
  enableOCI: "true"
