apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - name: cert-manager
            repoURL: https://charts.jetstack.io
            wave: "-5"
          - name: cloudflared
            repoURL: https://community-charts.github.io/helm-charts
            wave: "0"
          - name: cnpg-operator
            chart: cloudnative-pg
            repoURL: https://cloudnative-pg.github.io/charts
            namespace: cnpg-system
            wave: "-2"
          - name: external-secrets
            repoURL: https://charts.external-secrets.io
            namespace: external-secrets-system
            wave: "-2"
          - name: external-dns
            repoURL: https://kubernetes-sigs.github.io/external-dns/
            wave: "-2"
          - name: external-dns-openwrt
            chart: external-dns
            repoURL: https://kubernetes-sigs.github.io/external-dns/
            wave: "-2"
          - name: goldilocks
            repoURL: https://charts.fairwinds.com/stable
            wave: "0"
          - name: intel-device-plugins-operator
            repoURL: https://intel.github.io/helm-charts/
            namespace: kube-system
            wave: "-1"
          - name: intel-device-plugins-gpu
            repoURL: https://intel.github.io/helm-charts/
            namespace: kube-system
            wave: "0"
          - name: metrics-server
            repoURL: https://kubernetes-sigs.github.io/metrics-server/
            namespace: kube-system
            wave: "-3"
          - name: node-feature-discovery
            repoURL: https://kubernetes-sigs.github.io/node-feature-discovery/charts
            wave: "-1"
          - name: vault-autounseal
            repoURL: https://pytoshka.github.io/vault-autounseal
            namespace: vault
            wave: "1"
          - name: vpa
            repoURL: https://charts.fairwinds.com/stable
            wave: "0"
  template:
    metadata:
      name: "{{.name}}"
      namespace: argocd
    spec:
      project: infrastructure
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ dig \"namespace\" .name . }}"
  templatePatch: |
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "{{.wave}}"
      labels:
        app.kubernetes.io/managed-by: argocd-applicationset
        app.kubernetes.io/part-of: infrastructure
      finalizers:
        - resources-finalizer.argocd.argoproj.io/background
    spec:
      sources:
        - repoURL: "{{.repoURL}}"
          chart: "{{ dig "chart" .name . }}"
          targetRevision: "{{ dig "targetRevision" "*" . }}"
          helm:
            valueFiles:
              - "$values/values/infrastructure/{{.name}}.yaml"
        - repoURL: git@github.com:VizzleTF/home-proxmox-values.git
          targetRevision: HEAD
          ref: values
        - repoURL: git@github.com:VizzleTF/home-proxmox-values.git
          targetRevision: HEAD
          path: "manifests/infrastructure/{{.name}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
