apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: talos-etcd-backup
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-backend-cluster
    kind: ClusterSecretStore
  target:
    name: talos-etcd-backup
    creationPolicy: Owner
  data:
    - secretKey: config
      remoteRef:
        key: home/data/homelab/k8s/kube-system/talos-etcd-backup
        property: config
