data: 
  name: "vaultwarden-data"
  size: "2Gi"
  path: "/data"
  accessMode: "ReadWriteMany"
  # keepPvc: false

domain: "https://pass.internal.example"

ingress:
  enabled: true
  hostname: "pass.internal.example"
  class: "nginx"
  tlsSecret: vw-tls
  additionalAnnotations: 
    cert-manager.io/cluster-issuer: cloudflare-issuer