replicaCount: 1

strategy:
  type: Recreate

image:
  repository: ghcr.io/dannymcc/may
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 5050

env:
  SECRET_KEY: "change-me-to-random-secret-key"
  ADMIN_PASSWORD: "admin123"
  # DATABASE_URL: "sqlite:///data/may.db"
  # UPLOAD_FOLDER: "/app/data/uploads"

persistence:
  enabled: true
  storageClass: "longhorn"
  accessMode: ReadWriteOnce
  size: 5Gi
  mountPath: /app/data

resources:
  limits:
    cpu: 200m
    memory: 350Mi
  requests:
    cpu: 15m
    memory: 200Mi

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
