apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-backup-secret
  namespace: longhorn-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-backend-cluster
    kind: ClusterSecretStore
  target:
    name: longhorn-backup-secret
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: home/data/homelab/k8s/longhorn-system/s3-backup
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: home/data/homelab/k8s/longhorn-system/s3-backup
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: AWS_ENDPOINTS
      remoteRef:
        key: home/data/homelab/k8s/longhorn-system/s3-backup
        property: AWS_ENDPOINTS
    - secretKey: VIRTUAL_HOSTED_STYLE
      remoteRef:
        key: home/data/homelab/k8s/longhorn-system/s3-backup
        property: VIRTUAL_HOSTED_STYLE
