# External Secrets Operator Helm Values
# https://github.com/external-secrets/external-secrets

installCRDs: true
replicaCount: 2

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 32Mi

extraEnv:
  - name: GOMEMLIMIT
    value: "110MiB"

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65534

serviceMonitor:
  enabled: true

webhook:
  create: true
  port: 9443
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 32Mi
  extraEnv:
    - name: GOMEMLIMIT
      value: "110MiB"

certController:
  create: true
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 32Mi
  extraEnv:
    - name: GOMEMLIMIT
      value: "110MiB"