apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: openbao-backend-cluster
spec:
  provider:
    vault:
      server: "http://openbao.openbao.svc.cluster.local:8200"
      path: "home"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "homelab-universal"
          serviceAccountRef:
            name: "openbao-auth"
            namespace: "openbao"
