global:
  node_name: "pve1"
  datastore_id: "synology"
  upload_timeout: 3600
  overwrite: false
  
images:
  talos:
    enabled: false
    content_type: "import"
    url: "https://factory.talos.dev/image/eed1860a28ccc6fdb77f1f41ab0ae2a20c19bc6101618d416d5d72ec919bf679/v1.13.0-beta.1/metal-amd64.qcow2"
    file_name: "talos-1.13.0-beta.1.qcow2"

  talos-nocloud:
    enabled: true
    content_type: "import"
    # NoCloud image for cloud-init support (compressed)
    url: "https://factory.talos.dev/image/eed1860a28ccc6fdb77f1f41ab0ae2a20c19bc6101618d416d5d72ec919bf679/v1.13.0-beta.1/nocloud-amd64.qcow2"
    file_name: "talos-nocloud-1.13.0-beta.1.qcow2"