global:
  node_name: "pve1"
  datastore_id: "local-lvm"
  gateway: "10.11.11.1"
  dns_servers: ["10.11.12.1"]
  cores: 4
  ram: 2048
  disk_size: 20
  pool_id: null
  boot_order: ["sata0"]
  startup_order: 2
  startup_up_delay: 5
  cpu_type: "x86-64-v3"
  network_bridge: "vmbr0"
  os_type: "l26"

tags:
  - terraform

vms:
  talos-cp-01:
    node_name: "pve1"
    enabled: true
    vm_id: 501
    address: "10.11.11.101/24"
    tags: ["talos", "kubernetes"]
    description: "Talos Linux VM for Kubernetes cluster"
    image_file: "talos-nocloud"
    talos_config: "controlplane"
    vlan_id: "11"
    cores: 4
    ram: 14336
    disk_size: 300
    machine: "q35"
    cpu_type: "host"
    hostpci:
      - device: "hostpci0"
        id: "0000:00:02"
        pcie: true
        rombar: false
        xvga: false
  talos-cp-02:
    node_name: "pve2"
    enabled: true
    vm_id: 502
    address: "10.11.11.102/24"
    tags: ["talos", "kubernetes"]
    description: "Talos Linux VM for Kubernetes cluster"
    image_file: "talos-nocloud"
    talos_config: "controlplane"
    vlan_id: "11"
    cores: 4
    ram: 14336
    disk_size: 300
    machine: "q35"
    cpu_type: "host"
    hostpci:
      - device: "hostpci0"
        id: "0000:00:02.0"
        pcie: true
        rombar: false
        xvga: false
  talos-cp-03:
    node_name: "pve3"
    enabled: true
    vm_id: 503
    address: "10.11.11.103/24"
    tags: ["talos", "kubernetes"]
    description: "Talos Linux VM for Kubernetes cluster"
    image_file: "talos-nocloud"
    talos_config: "controlplane"
    vlan_id: "11"
    cores: 4
    ram: 14336
    disk_size: 125
    machine: "q35"
    cpu_type: "host"
    hostpci:
      - device: "hostpci0"
        id: "0000:00:02.0"
        pcie: true
        rombar: false
        xvga: false
  talos-worker-01:
    node_name: "pve4"
    enabled: true
    vm_id: 504
    address: "10.11.11.111/24"
    tags: ["talos", "kubernetes"]
    description: "Talos Linux VM for Kubernetes cluster"
    image_file: "talos-nocloud"
    talos_config: "worker"
    vlan_id: "11"
    cores: 4
    ram: 14336
    disk_size: 300
    machine: "q35"
    cpu_type: "host"
    hostpci:
      - device: "hostpci0"
        id: "0000:00:02.0"
        pcie: true
        rombar: false
        xvga: false
